### ISSUE TITLE
跨域怎么配置？

### ISSUE THREAD

**Issue by time100** [cklwblove/vue-cli3-template#2]
大神，开发模式怎么配置跨域呀？求指教

**Comment by cklwblove** [comment]
可以在 `vue.config.js`添加配置,相关代码如下：

```js
devServer: {
        proxy: {
            '/api': {
                target: 'http://www.example.org',
                changeOrigin: true,
                pathRewrite: {
                  '^/api': ''
                }
            }
        }
    }
```

**Comment by time100** [comment]
我是这样配置，但还是提示
![image](https://user-images.githubusercontent.com/14814790/51165639-e62b1b80-18db-11e9-86a3-bbb713610878.png)

**Comment by cklwblove** [comment]
你的截图再全些，这样看不出来啊，再尽量多的贴些关键性的代码

**Comment by time100** [comment]
![image](https://user-images.githubusercontent.com/14814790/51166732-79198500-18df-11e9-8845-7095b630eef9.png)
![image](https://user-images.githubusercontent.com/14814790/51166771-98181700-18df-11e9-8154-5fecb3ba2bc4.png)

浏览器直接访问接口是这样
![image](https://user-images.githubusercontent.com/14814790/51166811-b716a900-18df-11e9-9e50-dc2235503c04.png)

**Comment by cklwblove** [comment]
相关配置改下：
// 代理
```
proxy: {
      '/dream/*': {
        target: 'http://v.juhe.cn',
        changeOrigin: true,
      }
    }
```
// 请求相关
```
import axios from 'axios';
axios.get('/dream/category', {}).then((res) => {
        console.log(res);
      })
```
亲测可以
![image](https://user-images.githubusercontent.com/5652022/51169120-09f35f00-18e6-11e9-8297-2b957aa65bdc.png)

**Comment by time100** [comment]
嗯嗯，谢谢大神，这个可以了。
![image](https://user-images.githubusercontent.com/14814790/51170170-b7677200-18e8-11e9-8a91-b15135f113a0.png)

$services.octocat这样调用不可以吧。

//RESTFULLURL.js配置
`export default {
  "octocat": "dream/category"
}`

![image](https://user-images.githubusercontent.com/14814790/51169802-be41b500-18e7-11e9-98a4-aaea73843fcd.png)
