### ISSUE TITLE
你好，可不可以再问个问题，这个模板下vux怎么配置，求指点。。

### ISSUE THREAD

**Issue by time100** [cklwblove/vue-cli3-template#3]
新建的项目这样配置是可以的，这个模板下不懂怎么配置了
原来的配置是这样
`module.exports = {
    configureWebpack: config => {
        require('vux-loader').merge(config, {
            options: {},
            plugins: ['vux-ui']
        })
    },
    baseUrl: './'
}`

模板下的配置是
![image](https://user-images.githubusercontent.com/14814790/51579423-da52e100-1efb-11e9-8c8a-086ab9afea34.png)

**Comment by cklwblove** [comment]
@time100 可以参考 vux 的 issue, [https://github.com/airyland/vux-loader/issues/67](https://github.com/airyland/vux-loader/issues/67)

**Comment by cklwblove** [comment]
这个 issue 无关此项目，先关掉了
