### ISSUE TITLE
为什么不建议用此作为项目的基础模板

### ISSUE THREAD

**Issue by mcmf** [cklwblove/vue-cli3-template#6]
有什么弊端吗

**Comment by cklwblove** [comment]
> 有什么弊端吗

因为这里面包含的特性太多，项目依赖也很多，而且有些可能是项目中用不到的。比如自动上传指定服务器等。可以根据项目所需，引用

**Comment by mcmf** [comment]
那出一个简洁版的分支呗   参考参考

**Comment by cklwblove** [comment]
> 那出一个简洁版的分支呗 参考参考

结合 vue-cli3 的 preset 搭建基于 git repo 的前端项目模板，可以移步 [vue-preset](https://github.com/cklwblove/vue-preset)

**Comment by mcmf** [comment]
this.$services.request(url).then(res => {
        console.log(res)
      })

请求是这么用吗
