### ISSUE TITLE
如何适配scss

### ISSUE THREAD

**Issue by XinJiangQingMang** [cklwblove/vue-cli3-template#9]
有计划支持sass吗

**Comment by cklwblove** [comment]
其实用的是官方的 `vue-cli3` 脚手架创建的，所以针对 `sass`的解析都已经包含在内了。这点可以通过 `npm run inspect` 生成的 `output.js`得出答案。
所以涉及到以下3点改造：

1. 安装 `sass-loader` 及 `node-sass`。 具体命令：
```
npm i sass-loader node-sass --save-dev
```
2. 所有 `.less` 文件都需要**改造**成 `.sass`

3. `vue.config.js` 配置，具体代码行：https://github.com/cklwblove/vue-cli3-template/blob/dev/vue.config.js#L33

**Comment by mcmf** [comment]
谢谢

**Comment by mcmf** [comment]
http://h5player.bytedance.com/gettingStarted/#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F  我想引用这个 但是西瓜播放器这个是scss的 我安装sass-loader node-sass 后 他的样式不能加载进来 能不能指导一下怎么引入
